"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution:
    def findTheDifference(self, s: 'str', t: 'str') -> 'str':
        s_map = self.mapString(s)
        t_map = self.mapString(t)

        for key in t_map:
            if key not in s_map:
                return key
            elif s_map[key] != t_map[key]:
                return key

    def mapString(self, s):
        map_dict = {}
        for char in s:
            if char in map_dict:
                map_dict[char] += 1
            else:
                map_dict[char] = 1

        return map_dict
    